make go-xcat pass ShellCheck
xcat2/xcat-core pull request #6367
Opened 2019-07-05 09:06 UTC by samveen

### The PR is to partially fix issue #4610

### The modification include

## ShellChecks on go-xcat

### The UT result

````
samveen@samveen-X230:~/workspace/xcat-core/xCAT-server/share/xcat/tools$ shellcheck go-xcat && echo complete
complete
```

2024-07-31 16:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/xcat2/xcat-core?pullRequest=6367) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/xcat2/xcat-core?pullRequest=6367) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/xcat2/xcat-core?pullRequest=6367) it.</sub>

2024-08-01 05:15 UTC, samveen commented
This will need to be rebased on top of master, so I'm marking it WIP till I get a chance to rebase.

2024-08-19 17:00 UTC, samveen commented
The rebase is done. 

I've utilized the following commandline to check and test:

```
$ shellcheck -e SC2207,SC2317 go-xcat
```

Fixes for the checks SC2207 and SC2317 will required a drastic rewrite of go-xcat, for which I do not have the bandwidth right now. Maybe after six months. In the meantime, this is ready for testing and merging.

2024-09-10 21:26 UTC, Obihoernchen requested changes
Unfortunately this breaks go-xcat because of additional `"` chars.

current code:

```
[root@vm-test ~]# ./go-xcat install
Operating system:   linux
Architecture:       x86_64
Linux Distribution: almalinux
Version:            9.4
go-xcat Version:    1.0.53


Reading repositories ...... done

xCAT Core Packages
==================

Package Name                Installed                      In Repository                 
------------                ---------                      -------------                 
perl-xCAT                   (not installed)                2.16.5-snap202303030907       
xCAT                        (not installed)                2.16.5-snap202303030907       
[...]
```

with this PR:

```
[root@vm-test ~]# ./go-xcat-new install
Operating system:   linux
Architecture:       x86_64
Linux Distribution: "almalinux"
Version:            "9.4"
go-xcat-new: "almalinux": unsupported Linux distro
go-xcat-new Version: 1.0.53


Reading repositories ...... failed

Cache was expired
0 files removed
go-xcat-new: "almalinux""9: unsupported Linux distro
Cache was expired
0 files removed

Boo-boo
=======

Something went wrong. :(

Please check log file `/tmp/go-xcat.log' for more details.
```

2024-09-11 14:03 UTC, samveen commented
I'll check on this. PLease give me a couple of days.

2026-05-05 06:10 UTC, viniciusferrao commented
@samveen wanna check on that?

2026-05-08 00:01 UTC, Obihoernchen commented
Rebased and merged in #7569

2026-05-08 00:01 UTC, closed without merging