Add perl to the rhels8 pkglist
xcat2/xcat-core pull request #6836
Opened 2020-09-25 20:46 UTC by cxhong

For issue #6835 

The `perl` command is not install in the rhels8 compute node,   which cause post scripts failed to use perl command.

2020-09-28 12:33 UTC, besawn requested changes
@cxhong Do you think we should also update any of these other files:
```
xCAT-server/share/xcat/netboot/rh/compute.rhels8.ppc64le.pkglist
xCAT-server/share/xcat/install/rh/service.rhels8.pkglist
xCAT-server/share/xcat/install/centos/compute.centos8.pkglist
```
?

2020-09-28 13:32 UTC, cxhong commented
I will add `perl` to `xCAT-server/share/xcat/install/centos/compute.centos8.pkglist`

I verified `ppc64le`,  when node up, the `perl` command is installed.

2020-09-28 14:18 UTC, cxhong commented
without the `perl` command,  error messages showed in the `/var/log/xcat/xcat.log` on x86_64
```
Running Kickstart Post-installation script...
Mon Sep 28 07:09:08 EDT 2020 [info]: xcat.deployment: Executing post.xcat to prepare for firstbooting ...
/tmp/ks-script-byzbka30: line 140: perl: command not found
sleep: invalid time interval ''
Try 'sleep --help' for more information.
Mon Sep 28 07:09:09 EDT 2020 [info]: xcat.deployment: trying to download postscripts from 10.4.12.2...
````
on the ppc64le,  doesn't have this problem:
```
Running Kickstart Post-installation script...
Mon Sep 28 06:15:30 EDT 2020 [info]: xcat.deployment: Executing post.xcat to prepare for firstbooting ...
Mon Sep 28 06:15:31 EDT 2020 [info]: xcat.deployment: trying to download postscripts from 10.6.13.16...
```

2020-09-29 16:28 UTC, besawn approved these changes

2020-09-29 16:28 UTC, merged