xcatprobe fixes
xcat2/xcat-core pull request #6930
Opened 2021-03-25 20:06 UTC by gurevichmark

### The PR is to fix issue _#6929_

2021-04-06 15:51 UTC, besawn requested changes
The team conducted a group review of this PR and identified two changes that are needed.

2021-04-06 15:51 UTC, besawn commented on xCAT-probe/subcmds/xcatmn
> +
This logic needs to be modified in order to run on both MN and SN.

2021-04-06 15:51 UTC, besawn commented on xCAT-probe/subcmds/xcatmn
>                          $rc = 1;
This section should return from here rather than setting an rc and then returning at the bottom of the function.

2021-04-06 17:47 UTC, gurevichmark commented
Another commit added to fix issues identified during the review and grammar and spelling fixes.

2021-04-08 18:47 UTC, besawn approved these changes

2021-04-08 18:48 UTC, merged