Remove pidfile /dev/null for chronyd in setupntp on Ubuntu systems
xcat2/xcat-core pull request #6951
Opened 2021-04-21 20:03 UTC by peterwywong

The test case nodeset_cmdline fails on Ubuntu 18.04.2. This test case wants to load the genesis kernel on a compute node.

It turns out that the TFTP server does not run at this point.

Further investigation indicates that "chronyd ... "pidfile /dev/null"" turns the character-oriented device /dev/null into a text file /dev/null. By having that, the TFTP server stops working. Since the genesis kernel cannot be passed to the compute node through the TFTP server, the compute node loads whatever on its own hard drive.

This change removes "pidfile /dev/null" only if the management node runs a Ubuntu distro.

2021-04-21 20:14 UTC, gurevichmark commented on xCAT/postscripts/setupntp
> +OS_name=`cat /etc/os-release | grep "NAME=\"Ubuntu\""`
I think all postscript already get `OSVER` environment variable passed into them.
Perhaps that could be used instead of figuring it out again ?

2021-04-21 20:31 UTC, peterwywong commented on xCAT/postscripts/setupntp
> +OS_name=`cat /etc/os-release | grep "NAME=\"Ubuntu\""`
Great point.

In /install/postscripts/hardeths, OSVER is set in the script:
```
if [ -f /etc/os-release ] && (cat /etc/os-release |grep -i  '^NAME=[ "]*Cumulus Linux[ "]*$' >/dev/null 2>&1); then
    OSVER="cumulus"
fi

if [ -f /etc/os-release ] && (cat /etc/os-release |grep NAME|grep -i SLE >/dev/null); then
   OSVER="SLE"
fi
```
In /install/postscripts/syslog, it is assumed that $OSVER is set:
```
      if ( pmatch $OSVER "ubuntu*" ) || ( is_lsb_ubuntu ) || ( pmatch $OSVER "debian*" ); then
```
In many scripts, we have $OSVER and $ARCH, but **export** does not include them. Where are they defined?

As an experiment, **echo $OSVER** gives out nothing in setupntp.

2021-04-22 16:42 UTC, besawn requested changes
Please update line 148 from:
```
check_exec_or_exit cp cat logger
```
to
```
check_exec_or_exit cp cat logger grep
```
to account for the new dependency on grep.

2021-04-22 17:23 UTC, besawn approved these changes

2021-04-22 20:55 UTC, merged

2021-11-29 15:31 UTC, Obihoernchen commented
This is an issue on Rocky/Alma 8.5, too.

2021-12-08 22:50 UTC, peterwywong commented
Is it a permission denied problem on /dev/null?

Do you see this problem on Rocky 8.4?

Rocky 8.4 runs fine in the daily regression run going through "setupntp". We can add Rocky to the condition if needed.

2021-12-09 23:56 UTC, Obihoernchen commented
No chronyd or systemd will somehow remove the character special device and replace it with an empty file.
You can easily check it with file.

```
❯ file /dev/null
/dev/null: character special (1/3)
❯ # setupntp...
❯ file /dev/null
/dev/null: empty
```

Removing the pidfile option fixes this issue.

2022-02-15 10:19 UTC, URZ-HD commented
We have seen this issue also constantly on RHEL8.5. Removing the "pidfile /dev/null" from "pidfile_options" solves the problem.
So at least for RH8.5 there should be the same exclusion as for Ubuntu ...

2022-02-15 11:01 UTC, Obihoernchen commented
This is already the case https://github.com/xcat2/xcat-core/pull/7080