Redact passwords in log files
xcat2/xcat-core pull request #6998
Opened 2021-06-29 17:51 UTC by gurevichmark

### The PR is to fix issue _#6516_

Redact passwords strings so that they do not appear in log files.

2021-06-30 16:42 UTC, besawn requested changes

2021-06-30 16:42 UTC, besawn commented on xCAT-server/lib/perl/xCAT/xcatd.pm
> +                        # Replace password with the same number of 'x'
For security reasons, I don't think this should perform a 1 for 1 replacement of original characters with 'x' characters because this leaks information about the length of the original password. Can you re-work this to always replace a password with a fixed string such as "xxxxxxxx"?

2021-06-30 18:34 UTC, gurevichmark commented on xCAT-server/lib/perl/xCAT/xcatd.pm
> +                        # Replace password with the same number of 'x'
New commit added with fixed replacement string of 8 `x`. 
Log file now has:
```
====================================================
[Date]       2021-06-30 14:29:36
[ClientType] cli
[Request]    rspconfig f6u13k18 'admin_passwd=xxxxxxxx'
[Response]
f6u13k18: Error: Unable to identify plugin for this command, check relevant tables: nodehm.mgt=blade|fsp|ipmi;switches.switchtype;nodehm.mgt=openbmc
[NumberNodes] 1
[ElapsedTime] 0.048 s
```

2021-07-01 20:15 UTC, besawn approved these changes

2021-07-01 20:15 UTC, merged