Support VM machine types specified through vm.othersettings
xcat2/xcat-core pull request #7021
Opened 2021-08-17 22:12 UTC by peterwywong

This PR is to address https://github.com/xcat2/xcat-core/issues/6934.

Thanks to rbudden for providing the code. The comments are slightly enhanced.

2021-08-17 22:38 UTC, peterwywong commented
Note that Lines 714-718 are probably a piece of dead code:
```
    if (defined($hypcpumodel) and $hypcpumodel eq "ppc64") {
        $xtree{os}->{type}->{arch}    = "ppc64";
        $xtree{os}->{type}->{machine} = "pseries";
        delete $xtree{os}->{bios};
    }
```
The reason is that the latest POWER systems has the hypcpumodel as ppc64le, not ppc64.

In fact, {machine} is set by qemu if it is not set here.

It is definitely the case for x86_64.

2021-08-18 12:04 UTC, gurevichmark commented
> 
> 
> Note that Lines 714-718 are probably a piece of dead code:
> 
> ```
>     if (defined($hypcpumodel) and $hypcpumodel eq "ppc64") {
>         $xtree{os}->{type}->{arch}    = "ppc64";
>         $xtree{os}->{type}->{machine} = "pseries";
>         delete $xtree{os}->{bios};
>     }
> ```
> 
> The reason is that the latest POWER systems have the hypcpumodel as ppc64le, not ppc64.
> 
> In fact, {machine} is set by qemu if it is not set here.
> 
> It is definitely the case for ppc64le and x86_64.

The `ppc64` might be a valid `hypcpumodel` for Power7 hypervisors or earlier.

2021-08-18 12:13 UTC, gurevichmark requested changes
Man page for the `node` object needs to be updates to indicate that `machine:` is a valid key for `vmothersetting` attribute:

![image](https://user-images.githubusercontent.com/16106630/129895994-e0f66029-05eb-48eb-bc67-412d7a19ec53.png)

2021-08-20 15:23 UTC, peterwywong commented
I have made significant changes to the othersettings section of Schema.pm.
In addition to changing its presentation format, I clarify the meaning of each option. Please verify their correctness, in particular the one for PCI passthrough.

2021-08-20 16:38 UTC, peterwywong commented
It turns out that Mark has a PR for the Rocky-related rst files which are waiting to be merged.

create_man_pages.py for my othersettings changes n Schema.pm also generates those Rocky-related rst files.

To avoid this PR conflict, I will close this PR. Once Mark's rst files are merged, I will then re-submit kvm.pm, Schema.pm and its associated rst files.

2021-08-20 16:41 UTC, closed without merging

2021-08-20 18:11 UTC, gurevichmark commented on perl-xCAT/xCAT/Schema.pm
> +             Specify which host CPUs are used, e.g., 'vcpupin:'0-15,^8', where '-' denotes the range and '^' denotes exclusion. This option allows a comma-delimited list.
I think it should be `denotes exclusiveness` instead of `denotes exclusion`. `exclusion` means "being excluded", where as old test talks about being `exclusive`.

2021-08-20 18:11 UTC, gurevichmark commented on perl-xCAT/xCAT/Schema.pm
> +             Specify which host memmory modules are used, e.g., 'membind:0'. This option allows a guest to access specified memory regions.
Typo in `memmory`

2021-08-20 18:11 UTC, gurevichmark commented on perl-xCAT/xCAT/Schema.pm
> +             Specify which host memmory modules are used, e.g., 'membind:0'. This option allows a guest to access specified memory regions.
The old writeup says `specified set of NUMA nodes`. It is not applicable ?