mysqlsetup enhancements
xcat2/xcat-core pull request #7337
Opened 2023-02-14 18:26 UTC by gurevichmark

This PR:

* Updates `mysqlsetup` script to run on RHEL9 by detecting correct name of the running process - `mariadbd` in addition to `mysqld`.
* Updated `mysqlsetup` man page and related documentation to fix typos and formatting.

2023-02-16 18:57 UTC, besawn requested changes

2023-02-16 18:57 UTC, besawn commented on xCAT-client/bin/mysqlsetup
> +    my @db_service_name_list = ("mysqld", "mariadb");
The way this is currently structured guarantees that the script will sit around checking for `mysqld` for 60 seconds before attempting to check to see if `mariadb` is running.

I think it would be better to pull the `foreach my $db_service_name` inside of the `for (my $i = 0 ; $i < 6; i++)` loop so both process names can get checked on each loop.

Something more like this:
```
        for (my $i = 0 ; $i < 6 ; $i++) {
           my @db_service_name_list = ("mysqld", "mariadb");
           foreach my $db_service_name (@db_service_name_list) {
              $cmd = "ps -ef | grep $db_service_name | grep -v grep";
               my @output = xCAT::Utils->runcmd($cmd, 0);
               my $mysqlcheck = $db_service_name;

               if (grep(/$mysqlcheck/, @output)) {
                   sleep 10;    # give a few extra seconds to be sure
                   return;
               } else {
                   sleep 10;    # wait for daemon
               }
            }   
        }
```

2023-02-17 17:26 UTC, gurevichmark commented on xCAT-client/bin/mysqlsetup
> +    my @db_service_name_list = ("mysqld", "mariadb");
Yes, I agree. As discussed, made this check more efficient, so we do not have to sit and keep checking for the process that might never appear.

#### UT on RH9 running `mariadbd`:
```
[root@vm-229 xcat]# XCATMYSQLADMIN_PW=12345 XCATMYSQLROOT_PW=12345 /opt/xcat/bin/mysqlsetup -i -V
Running command on vm-229: rpm -qa | grep -i mariadb 2>&1

Running command on vm-229: rpm -qa | grep -i perl-DBD-mysql 2>&1

Running command on vm-229: pidof mysqld 2>&1

Command failed: pidof mysqld 2>&1. Error message: .
Running command on vm-229: pidof mariadbd 2>&1

MariaDB is already running. Database initialization will not take place.
Running command on vm-229: fgrep mysql /etc/xcat/cfgloc 2>&1

Running command on vm-229: sed 's/^bind/#&/' /etc/my.cnf > /tmp/my.cnf; mv -f /tmp/my.cnf /etc/my.cnf;chmod 644 /etc/my.cnf 2>&1

Running command on vm-229: /usr/bin/mysql_install_db --user=mysql 2>&1

Running command on vm-229: ps -ef | grep -E 'mariadbd|mysqld' | grep -v grep 2>&1

Running command on vm-229: chkconfig mariadb on 2>&1

:
:
:
```

#### UT on RH8 running `mysqld`:
```
[root@c910f04x37v05 xcat]# XCATMYSQLADMIN_PW=12345 XCATMYSQLROOT_PW=12345 /opt/xcat/bin/mysqlsetup -i -V
Running command on c910f04x37v05: rpm -qa | grep -i mariadb 2>&1

Running command on c910f04x37v05: rpm -qa | grep -i perl-DBD-mysql 2>&1

Running command on c910f04x37v05: pidof mysqld 2>&1

MySQL is already running. Database initialization will not take place.
Running command on c910f04x37v05: pidof mariadbd 2>&1

Command failed: pidof mariadbd 2>&1. Error message: .

Running command on c910f04x37v05: sed 's/^bind/#&/' /etc/my.cnf > /tmp/my.cnf; mv -f /tmp/my.cnf /etc/my.cnf;chmod 644 /etc/my.cnf 2>&1

Running command on c910f04x37v05: /usr/bin/mysql_install_db --user=mysql 2>&1

Running command on c910f04x37v05: ps -ef | grep -E 'mariadbd|mysqld' | grep -v grep 2>&1

Running command on c910f04x37v05: chkconfig mariadb on 2>&1

:
:
:
```

2023-02-17 18:34 UTC, besawn approved these changes
Looks good, thanks!

2023-02-17 18:35 UTC, merged