Use 'nmcli con modify' for nicextraparams on RHEL9
xcat2/xcat-core pull request #7444
Opened 2024-05-28 16:07 UTC by alexrichert

### The PR is to address issue #7416 

### The modification include

##update to xCAT/postscripts/nicutils.sh to include RHEL9-specific logic in `add_extra_params_nmcli()` which calls `nmcli connection modify` instead of writing to ifcfg files.

### The UT result
`##The UT output##`

2024-05-29 06:02 UTC, samveen commented on xCAT/postscripts/configeth
> +            value="${array_extra_param_values[$i]}"
please fix your code formatting settings to match the xCAT coding standards, as the indentation is no longer correct.

2024-06-11 09:11 UTC, Obihoernchen requested changes
Please add matching strings for alma9* and rocky9*, too.

2024-06-11 16:24 UTC, alexrichert commented
@Obihoernchen to be clear, when you say similar logic, do you mean using nmcli calls instead of the ifcfg files?

2024-06-24 08:58 UTC, Obihoernchen requested changes
There is some Space/Tab indentation mixup. Can you please fix this? Otherwise it looks good.

2024-06-24 21:31 UTC, Obihoernchen approved these changes

2024-06-24 21:35 UTC, merged

2024-07-03 00:11 UTC, landcaster commented
Not sure if this is the appropriate place to report this and if this is specific to our site, but this merge breaks infiniband configuration on our Rocky 9 cluster.

The error response we got in the script logs for configib is:
"nmcli Error: unknown connection" 

Digging into this, the IB looks to never have been connected via "nmcli con add " before calls  to "nmcli con modify" are made.

I modified the configib script after Line 491 to make the following call instead of trying to write an ifcfg-$nic file.   
```
elif [ $OS_name == 'redhat' ]
 then
   # First ip address
   if [ $ipindex -eq 1 ]
     ###
     if [[ "$OSVER" =~ (rhels9|alma9|rocky9) ]]; then
       prefix=$(convert_netmask_to_cidr $netmask)
       nmcli con add type infiniband con-name $nic ifname $nic ipv4.method manual  ipv4.addresses  $nicip/$prefix connection.autoconnect-priority 9
     else 
       ...
     fi
   ....
```

I can possibly work on creating a pull request to address this, but it might take me awhile as I am a bit short on free time.
As far as how to approach the problem, it is not clear to me if copying the configipv4 and configipv6 function in the configeth script with the appropriate changes would be a good approach to take as I would assume those functions have had extensive work already done to cover many of the cases one would encounter with xcat.

2024-07-03 09:01 UTC, Obihoernchen commented
Thank you for your report. I'll take a look at it.